const PDFDocument = require('pdfkit');
const PDFTable = require('pdfkit-table');

// Shared brand colors
const COLORS = {
  primary: '#6366f1',      // indigo
  dark: '#0f172a',         // navy
  text: '#1e293b',         // dark slate
  subtext: '#64748b',      // gray
  success: '#22c55e',      // green
  danger: '#ef4444',       // red
  warning: '#f59e0b',      // amber
  white: '#ffffff',
  lightGray: '#f8fafc',
  border: '#e2e8f0'
};

// Shared header function — used by all 3 reports
const addReportHeader = (doc, title, subtitle, dateRange) => {
  // Dark navy header bar
  doc.rect(0, 0, doc.page.width, 80)
     .fill(COLORS.dark);
  
  // AttendX brand name
  doc.fillColor(COLORS.white)
     .fontSize(24)
     .font('Helvetica-Bold')
     .text('AttendX', 40, 20);
  
  // Tagline
  doc.fillColor(COLORS.primary)
     .fontSize(10)
     .font('Helvetica')
     .text('HR Management System', 40, 48);
  
  // Report title on right
  doc.fillColor(COLORS.white)
     .fontSize(14)
     .font('Helvetica-Bold')
     .text(title, 0, 25, { align: 'right', 
       width: doc.page.width - 40 });
  
  // Subtitle on right
  doc.fillColor('#94a3b8')
     .fontSize(9)
     .font('Helvetica')
     .text(subtitle, 0, 45, { align: 'right', 
       width: doc.page.width - 40 });

  // Move below header
  doc.moveDown(2);

  // Date range + generated at info bar
  doc.fillColor(COLORS.subtext)
     .fontSize(9)
     .text(
       `Period: ${dateRange.from} to ${dateRange.to}  |  ` +
       `Generated: ${new Date().toLocaleString('en-IN', {
         timeZone: 'Asia/Kolkata'
       })}  |  Generated by: AttendX Admin`,
       40, 90
     );
  
  // Divider line
  doc.moveTo(40, 108)
     .lineTo(doc.page.width - 40, 108)
     .strokeColor(COLORS.border)
     .stroke();

  doc.moveDown(2);
};

// Shared footer function
const addPageFooter = (doc) => {
  const pageCount = doc.bufferedPageRange().count;
  for (let i = 0; i < pageCount; i++) {
    doc.switchToPage(i);
    
    // Footer line
    doc.moveTo(40, doc.page.height - 40)
       .lineTo(doc.page.width - 40, doc.page.height - 40)
       .strokeColor(COLORS.border)
       .stroke();
    
    // Footer text
    doc.fillColor(COLORS.subtext)
       .fontSize(8)
       .text(
         'This is a system-generated report from AttendX HR System. ' +
         'Do not alter this document.',
         40, doc.page.height - 28,
         { align: 'left' }
       );
    
    // Page number
    doc.text(
      `Page ${i + 1} of ${pageCount}`,
      0, doc.page.height - 28,
      { align: 'right', width: doc.page.width - 40 }
    );
  }
};

// Shared employee info card
const addEmployeeInfoCard = (doc, employee) => {
  // Light gray card background
  doc.rect(40, doc.y, doc.page.width - 80, 60)
     .fill(COLORS.lightGray);
  
  const cardY = doc.y + 10;
  
  doc.fillColor(COLORS.text)
     .fontSize(11)
     .font('Helvetica-Bold')
     .text(employee.name, 55, cardY);
  
  doc.fillColor(COLORS.subtext)
     .fontSize(9)
     .font('Helvetica')
     .text(
       `ID: ${employee.employeeId}  |  ` +
       `Email: ${employee.email}  |  ` +
       `Department: ${employee.department || 'N/A'}`,
       55, cardY + 18
     );
  
  doc.text(
    `Role: ${employee.role}  |  ` +
    `Joining Date: ${employee.joiningDate 
      ? new Date(employee.joiningDate)
          .toLocaleDateString('en-IN') 
      : 'N/A'}`,
    55, cardY + 33
  );
  
  doc.moveDown(4);
};

const addAttendanceSection = async (doc, emp, records, dateRange) => {
  // Summary stats row
  const present = records.filter(r => r.status === 'present').length;
  const late = records.filter(r => r.status === 'late').length;
  const absent = records.filter(r => r.status === 'absent').length;
  const onLeave = records.filter(r => r.status === 'on-leave' || r.status === 'leave').length;
  const totalDays = records.length;
  const workingDays = present + late;

  // Stats boxes (4 across)
  const statsY = doc.y;
  const boxWidth = (doc.page.width - 80) / 4;
  const statsData = [
    { label: 'Present', value: present, color: COLORS.success },
    { label: 'Late', value: late, color: COLORS.warning },
    { label: 'Absent', value: absent, color: COLORS.danger },
    { label: 'On Leave', value: onLeave, color: COLORS.primary }
  ];

  statsData.forEach((stat, i) => {
    const x = 40 + (i * boxWidth);
    doc.rect(x, statsY, boxWidth - 5, 45).fill(COLORS.lightGray);
    doc.fillColor(stat.color)
       .fontSize(20)
       .font('Helvetica-Bold')
       .text(stat.value.toString(), x, statsY + 5, 
         { width: boxWidth - 5, align: 'center' });
    doc.fillColor(COLORS.subtext)
       .fontSize(8)
       .font('Helvetica')
       .text(stat.label, x, statsY + 28,
         { width: boxWidth - 5, align: 'center' });
  });

  doc.moveDown(4);

  // Attendance table
  const table = {
    headers: [
      { label: 'Date', width: 80 },
      { label: 'Day', width: 60 },
      { label: 'Check In', width: 80 },
      { label: 'Check Out', width: 80 },
      { label: 'Working Hrs', width: 80 },
      { label: 'Break', width: 60 },
      { label: 'Status', width: 70 }
    ],
    rows: records.map(record => {
      const checkIn = record.checkIn 
        ? new Date(record.checkIn).toLocaleTimeString(
            'en-IN', { timeZone: 'Asia/Kolkata', 
              hour12: true }
          )
        : '—';
      const checkOut = record.checkOut
        ? new Date(record.checkOut).toLocaleTimeString(
            'en-IN', { timeZone: 'Asia/Kolkata', 
              hour12: true }
          )
        : '—';
      const workingHrs = record.totalWorkingHours
        ? `${Math.floor(record.totalWorkingHours / 60)}h ` +
          `${record.totalWorkingHours % 60}m`
        : '—';
      const breakTime = record.break?.durationMinutes || record.totalBreakTime
        ? `${record.break?.durationMinutes || record.totalBreakTime}m`
        : '—';
      const dayName = new Date(record.date)
        .toLocaleDateString('en-IN', { weekday: 'short' });

      return [
        record.date,
        dayName,
        checkIn,
        checkOut,
        workingHrs,
        breakTime,
        record.status?.toUpperCase() || '—'
      ];
    })
  };

  await doc.table(table, {
    prepareHeader: () => {
      doc.font('Helvetica-Bold').fontSize(9).fillColor(COLORS.white);
    },
    prepareRow: (row, indexColumn, indexRow) => {
      doc.font('Helvetica').fontSize(8).fillColor(COLORS.text);
      if (indexRow % 2 === 0) {
        doc.rect(40, doc.y, doc.page.width - 80, 20).fill(COLORS.lightGray);
      }
    },
    headerColor: COLORS.dark,
    headerOpacity: 1,
    columnSpacing: 5,
    padding: 5,
    x: 40,
    width: doc.page.width - 80
  });

  // Summary line at bottom
  doc.moveDown();
  doc.fillColor(COLORS.text)
     .fontSize(10)
     .font('Helvetica-Bold')
     .text(`Total Working Days: ${workingDays} / ${totalDays}  |  Attendance Rate: ${totalDays > 0 ? Math.round((workingDays/totalDays)*100) : 0}%`, 40, doc.y);
};

const generateAttendancePDF = async (
  res, employee, attendanceRecords, dateRange
) => {
  const doc = new PDFTable({ 
    margin: 40,
    size: 'A4',
    bufferPages: true
  });

  // Stream directly to response
  res.setHeader('Content-Type', 'application/pdf');
  res.setHeader(
    'Content-Disposition',
    `attachment; filename="attendance_${employee.employeeId}` +
    `_${dateRange.from}_${dateRange.to}.pdf"`
  );
  doc.pipe(res);

  // Header
  addReportHeader(
    doc,
    'Attendance Report',
    `${employee.name} — ${dateRange.from} to ${dateRange.to}`,
    dateRange
  );

  // Employee info card
  addEmployeeInfoCard(doc, employee);

  // 🏆 Reusable Attendance Section
  await addAttendanceSection(doc, employee, attendanceRecords, dateRange);

  addPageFooter(doc);
  doc.end();
};

const generatePayslipPDF = async (
  res, employee, payrollData, dateRange
) => {
  const doc = new PDFDocument({ 
    margin: 40, 
    size: 'A4',
    bufferPages: true
  });

  res.setHeader('Content-Type', 'application/pdf');
  res.setHeader(
    'Content-Disposition',
    `attachment; filename="payslip_${employee.employeeId}` +
    `_${payrollData.month}_${payrollData.year}.pdf"`
  );
  doc.pipe(res);

  addReportHeader(
    doc,
    'Payslip',
    `${payrollData.month} ${payrollData.year}`,
    dateRange
  );

  addEmployeeInfoCard(doc, employee);

  // Payslip two-column layout
  const leftX = 40;
  const rightX = doc.page.width / 2 + 10;
  const colWidth = (doc.page.width - 80) / 2 - 10;
  const startY = doc.y;

  // LEFT: Earnings
  doc.rect(leftX, startY, colWidth, 20)
     .fill(COLORS.dark);
  doc.fillColor(COLORS.white)
     .fontSize(10)
     .font('Helvetica-Bold')
     .text('EARNINGS', leftX + 10, startY + 5, 
       { width: colWidth });

  const earningsItems = [
    { label: 'Basic Salary', amount: payrollData.basicSalary },
    { label: 'HRA', 
      amount: Math.round(payrollData.basicSalary * 0.4) },
    { label: 'Transport Allowance', amount: 1600 },
    { label: 'Bonus', amount: payrollData.bonus || 0 },
  ];

  let earningsY = startY + 25;
  let totalEarnings = 0;
  earningsItems.forEach((item, i) => {
    if (item.amount > 0) {
      const rowBg = i % 2 === 0 ? COLORS.lightGray : COLORS.white;
      doc.rect(leftX, earningsY, colWidth, 18).fill(rowBg);
      doc.fillColor(COLORS.text)
         .fontSize(9)
         .font('Helvetica')
         .text(item.label, leftX + 8, earningsY + 4);
      doc.text(
        `₹${item.amount.toLocaleString('en-IN')}`,
        leftX, earningsY + 4,
        { width: colWidth - 8, align: 'right' }
      );
      totalEarnings += item.amount;
      earningsY += 18;
    }
  });

  // Earnings total
  doc.rect(leftX, earningsY, colWidth, 22).fill(COLORS.primary);
  doc.fillColor(COLORS.white)
     .fontSize(10)
     .font('Helvetica-Bold')
     .text('Total Earnings', leftX + 8, earningsY + 5);
  doc.text(
    `₹${totalEarnings.toLocaleString('en-IN')}`,
    leftX, earningsY + 5,
    { width: colWidth - 8, align: 'right' }
  );

  // RIGHT: Deductions
  doc.rect(rightX, startY, colWidth, 20).fill(COLORS.danger);
  doc.fillColor(COLORS.white)
     .fontSize(10)
     .font('Helvetica-Bold')
     .text('DEDUCTIONS', rightX + 10, startY + 5,
       { width: colWidth });

  const deductionItems = [
    { label: 'PF (12%)', 
      amount: Math.round(payrollData.basicSalary * 0.12) },
    { label: 'Professional Tax', amount: 200 },
    { label: 'Absent Deduction', 
      amount: payrollData.absentDeduction || 0 },
    { label: 'Late Deduction', 
      amount: payrollData.lateDeduction || 0 },
  ];

  let deductionsY = startY + 25;
  let totalDeductions = 0;
  deductionItems.forEach((item, i) => {
    if (item.amount > 0) {
      const rowBg = i % 2 === 0 ? COLORS.lightGray : COLORS.white;
      doc.rect(rightX, deductionsY, colWidth, 18).fill(rowBg);
      doc.fillColor(COLORS.text)
         .fontSize(9)
         .font('Helvetica')
         .text(item.label, rightX + 8, deductionsY + 4);
      doc.text(
        `₹${item.amount.toLocaleString('en-IN')}`,
        rightX, deductionsY + 4,
        { width: colWidth - 8, align: 'right' }
      );
      totalDeductions += item.amount;
      deductionsY += 18;
    }
  });

  // Deductions total
  doc.rect(rightX, deductionsY, colWidth, 22).fill(COLORS.danger);
  doc.fillColor(COLORS.white)
     .fontSize(10)
     .font('Helvetica-Bold')
     .text('Total Deductions', rightX + 8, deductionsY + 5);
  doc.text(
    `₹${totalDeductions.toLocaleString('en-IN')}`,
    rightX, deductionsY + 5,
    { width: colWidth - 8, align: 'right' }
  );

  // NET SALARY box — full width, prominent
  const netY = Math.max(earningsY, deductionsY) + 30;
  const netSalary = totalEarnings - totalDeductions;

  doc.rect(40, netY, doc.page.width - 80, 50)
     .fill(COLORS.dark);
  doc.fillColor(COLORS.white)
     .fontSize(13)
     .font('Helvetica-Bold')
     .text('NET SALARY', 55, netY + 10);
  doc.fillColor(COLORS.primary)
     .fontSize(22)
     .font('Helvetica-Bold')
     .text(
       `₹${netSalary.toLocaleString('en-IN')}`,
       0, netY + 8,
       { align: 'right', width: doc.page.width - 55 }
     );

  // Attendance summary below net salary
  doc.moveDown(5);
  doc.fillColor(COLORS.text)
     .fontSize(10)
     .font('Helvetica-Bold')
     .text('Attendance Summary', 40, doc.y);
  doc.moveDown(0.5);

  const attSummary = [
    ['Working Days', payrollData.workingDays || '—'],
    ['Present Days', payrollData.presentDays || '—'],
    ['Absent Days', payrollData.absentDays || '—'],
    ['Late Days', payrollData.lateDays || '—'],
    ['Leave Days', payrollData.onLeaveDays || '—'],
  ];

  attSummary.forEach(([label, value], i) => {
    const rowY = doc.y;
    const rowBg = i % 2 === 0 ? COLORS.lightGray : COLORS.white;
    doc.rect(40, rowY, doc.page.width - 80, 18).fill(rowBg);
    doc.fillColor(COLORS.text)
       .fontSize(9)
       .font('Helvetica')
       .text(label, 55, rowY + 4);
    doc.text(value.toString(), 0, rowY + 4,
      { align: 'right', width: doc.page.width - 55 });
    doc.moveDown(1.2);
  });

  addPageFooter(doc);
  doc.end();
};

const generateLeaveReportPDF = async (
  res, employee, leaveRecords, leaveBalance, dateRange
) => {
  const doc = new PDFTable({ 
    margin: 40, 
    size: 'A4',
    bufferPages: true
  });

  res.setHeader('Content-Type', 'application/pdf');
  res.setHeader(
    'Content-Disposition',
    `attachment; filename="leave_report_` +
    `${employee.employeeId}_${dateRange.from}` +
    `_${dateRange.to}.pdf"`
  );
  doc.pipe(res);

  addReportHeader(
    doc,
    'Leave Report',
    `${employee.name} — ${dateRange.from} to ${dateRange.to}`,
    dateRange
  );

  addEmployeeInfoCard(doc, employee);

  // Leave balance summary cards
  const balanceY = doc.y;
  const balanceTypes = [
    { type: 'Sick Leave', 
      total: leaveBalance.sick?.total || 0,
      used: leaveBalance.sick?.used || 0,
      color: COLORS.danger },
    { type: 'Casual Leave',
      total: leaveBalance.casual?.total || 0,
      used: leaveBalance.casual?.used || 0,
      color: COLORS.warning },
    { type: 'Earned Leave',
      total: leaveBalance.earned?.total || 0,
      used: leaveBalance.earned?.used || 0,
      color: COLORS.success },
  ];

  const cardW = (doc.page.width - 80) / 3;
  balanceTypes.forEach((bal, i) => {
    const x = 40 + (i * cardW);
    doc.rect(x, balanceY, cardW - 5, 55).fill(COLORS.lightGray);
    doc.fillColor(bal.color)
       .fontSize(9)
       .font('Helvetica-Bold')
       .text(bal.type, x + 8, balanceY + 8,
         { width: cardW - 16 });
    doc.fillColor(COLORS.text)
       .fontSize(18)
       .font('Helvetica-Bold')
       .text(
         `${bal.total - bal.used}`,
         x, balanceY + 22,
         { width: cardW - 5, align: 'center' }
       );
    doc.fillColor(COLORS.subtext)
       .fontSize(8)
       .font('Helvetica')
       .text(
         `${bal.used} used of ${bal.total}`,
         x, balanceY + 42,
         { width: cardW - 5, align: 'center' }
       );
  });

  doc.moveDown(5);

  // Leave history table
  doc.fillColor(COLORS.text)
     .fontSize(11)
     .font('Helvetica-Bold')
     .text('Leave History', 40, doc.y);
  doc.moveDown(0.5);

  const leaveTable = {
    headers: [
      { label: 'Applied On', width: 80 },
      { label: 'Leave Type', width: 90 },
      { label: 'From', width: 75 },
      { label: 'To', width: 75 },
      { label: 'Days', width: 40 },
      { label: 'Reason', width: 120 },
      { label: 'Status', width: 70 }
    ],
    rows: leaveRecords.map(leave => [
      new Date(leave.createdAt)
        .toLocaleDateString('en-IN'),
      leave.leaveType || '—',
      new Date(leave.startDate)
        .toLocaleDateString('en-IN'),
      new Date(leave.endDate)
        .toLocaleDateString('en-IN'),
      leave.totalDays?.toString() || '—',
      (leave.reason || '—').substring(0, 40) +
        (leave.reason?.length > 40 ? '...' : ''),
      (leave.status || '—').toUpperCase()
    ])
  };

  await doc.table(leaveTable, {
    prepareHeader: () => {
      doc.font('Helvetica-Bold')
         .fontSize(8)
         .fillColor(COLORS.white);
    },
    prepareRow: (row, indexColumn, indexRow) => {
      doc.font('Helvetica')
         .fontSize(8)
         .fillColor(COLORS.text);
      if (indexRow % 2 === 0) {
        doc.rect(
          40, doc.y, doc.page.width - 80, 20
        ).fill(COLORS.lightGray);
      }
    },
    headerColor: COLORS.dark,
    columnSpacing: 5,
    padding: 5,
    x: 40,
    width: doc.page.width - 80
  });

  addPageFooter(doc);
  doc.end();
};

module.exports = {
  addReportHeader,
  addEmployeeInfoCard,
  addPageFooter,
  addAttendanceSection,
  generateAttendancePDF,
  generatePayslipPDF,
  generateLeaveReportPDF
};
